<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/04pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train test splilt


In [5]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling

In [6]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [7]:
X_train

array([[-0.27382169, -0.47318965, -0.33310614, ..., -0.9948746 ,
        -0.2456051 , -0.66677111],
       [ 0.03403738, -0.61388081, -0.08081006, ..., -1.24077141,
        -0.72547348, -1.25893634],
       [-0.65793943, -0.18027528, -0.58662894, ...,  0.58084775,
         2.8510213 ,  3.08067895],
       ...,
       [-0.31618762, -0.20564581, -0.29385099, ...,  0.14823761,
         0.29172325, -0.05208383],
       [-0.66641261, -0.4824153 , -0.6953984 , ..., -1.09461527,
         0.42683183, -1.00844715],
       [ 1.47730328,  0.92680268,  1.505752  , ...,  0.60788588,
        -0.00800037, -0.43825466]])

In [8]:
y_train

246    B
270    B
31     M
410    B
527    B
      ..
418    B
547    B
356    B
188    B
244    M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [9]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [10]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,

In [11]:
type(y_train)

numpy.ndarray

Numpy array to pyTorch tensors

In [12]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-0.2738, -0.4732, -0.3331,  ..., -0.9949, -0.2456, -0.6668],
        [ 0.0340, -0.6139, -0.0808,  ..., -1.2408, -0.7255, -1.2589],
        [-0.6579, -0.1803, -0.5866,  ...,  0.5808,  2.8510,  3.0807],
        ...,
        [-0.3162, -0.2056, -0.2939,  ...,  0.1482,  0.2917, -0.0521],
        [-0.6664, -0.4824, -0.6954,  ..., -1.0946,  0.4268, -1.0084],
        [ 1.4773,  0.9268,  1.5058,  ...,  0.6079, -0.0080, -0.4383]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
X_train_tensor[1].shape

torch.Size([30])

Defining the model

In [16]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_fn(self,y_pred,y):
    #Clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #Calculate loss cross entropy
    loss=-(y_train_tensor*torch.log(y_pred)+ (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

Important Parameters

In [17]:
learning_rate=0.1
epochs=50

Training Pipeline

In [18]:
#create model
model=MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_fn(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #update parameter
  with torch.no_grad():
        model.weights -=learning_rate * model.weights.grad
        model.bias -=learning_rate *model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")



Epoch: 1, Loss: 3.8221703285066546
Epoch: 2, Loss: 3.6958113869708633
Epoch: 3, Loss: 3.5629183178101127
Epoch: 4, Loss: 3.427288190025058
Epoch: 5, Loss: 3.2864994051884215
Epoch: 6, Loss: 3.1434609537033626
Epoch: 7, Loss: 2.994734791483435
Epoch: 8, Loss: 2.840690954574137
Epoch: 9, Loss: 2.68443647365201
Epoch: 10, Loss: 2.530233587381941
Epoch: 11, Loss: 2.3764572671775936
Epoch: 12, Loss: 2.2231799121771005
Epoch: 13, Loss: 2.0714404702362845
Epoch: 14, Loss: 1.9241228693857755
Epoch: 15, Loss: 1.7715646234929396
Epoch: 16, Loss: 1.6302854982129873
Epoch: 17, Loss: 1.500658854531793
Epoch: 18, Loss: 1.3811451484002233
Epoch: 19, Loss: 1.2730244450651194
Epoch: 20, Loss: 1.1803725234342577
Epoch: 21, Loss: 1.102861815800374
Epoch: 22, Loss: 1.0393906870610254
Epoch: 23, Loss: 0.9882006462716487
Epoch: 24, Loss: 0.947177409326895
Epoch: 25, Loss: 0.914184374034128
Epoch: 26, Loss: 0.887312299531464
Epoch: 27, Loss: 0.8650154517439601
Epoch: 28, Loss: 0.8461404243658702
Epoch: 29, L

In [19]:
model.bias

tensor([-0.2520], dtype=torch.float64, requires_grad=True)

Evalution

In [20]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  # print(y_pred)
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5886426568031311


Defining the model using nn module


In [21]:
#create model class
import torch
import torch.nn as nn

In [30]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out



In [31]:
learning_rate=0.1
epochs=50

In [33]:
loss_function=nn.BCELoss()

In [34]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
#define optimizer
optimizer=torch.optim.SGD()

In [38]:
#create module
model=MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
for epoch in range(epochs):

  # forward pass
  y_pred=model.forward(X_train_tensor.float())

  #loss calculate
  loss=loss_function(y_pred,y_train_tensor.view(-1,1).float())

  #clear gradients()
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  #parameter update
  # with torch.no_grad():
  #   model.linear.weight-=learning_rate*model.linear.weight.grad
  #   model.linear.bias-=learning_rate*model.linear.bias.grad
  optimizer.step()
  #  zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.627449095249176
Epoch: 2, Loss: 0.48168137669563293
Epoch: 3, Loss: 0.40485480427742004
Epoch: 4, Loss: 0.356883704662323
Epoch: 5, Loss: 0.32355207204818726
Epoch: 6, Loss: 0.2987590730190277
Epoch: 7, Loss: 0.27942249178886414
Epoch: 8, Loss: 0.2638060450553894
Epoch: 9, Loss: 0.25085294246673584
Epoch: 10, Loss: 0.23988066613674164
Epoch: 11, Loss: 0.2304278463125229
Epoch: 12, Loss: 0.22217048704624176
Epoch: 13, Loss: 0.2148737907409668
Epoch: 14, Loss: 0.20836317539215088
Epoch: 15, Loss: 0.20250582695007324
Epoch: 16, Loss: 0.19719870388507843
Epoch: 17, Loss: 0.19236035645008087
Epoch: 18, Loss: 0.18792559206485748
Epoch: 19, Loss: 0.18384134769439697
Epoch: 20, Loss: 0.18006406724452972
Epoch: 21, Loss: 0.17655743658542633
Epoch: 22, Loss: 0.17329099774360657
Epoch: 23, Loss: 0.17023897171020508
Epoch: 24, Loss: 0.1673792004585266
Epoch: 25, Loss: 0.16469280421733856
Epoch: 26, Loss: 0.16216328740119934
Epoch: 27, Loss: 0.15977628529071808
Epoch: 28, Loss: 0.