<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/04pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train test splilt


In [5]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling

In [6]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [7]:
X_train

array([[-1.25002626, -1.46108665, -1.13635416, ..., -0.12398586,
        -0.11325505,  2.88936839],
       [ 1.91533036,  1.71918141,  2.02170489, ...,  2.64334491,
         1.8668197 ,  2.44804316],
       [-0.2228245 ,  2.70191502, -0.24335248, ..., -0.57617498,
        -1.14606205, -0.40126284],
       ...,
       [ 0.01844589,  0.5706855 ,  0.04962602, ...,  0.43916898,
         1.06370138,  0.95857052],
       [-0.55561125,  0.28652156, -0.60987702, ..., -0.62643503,
        -0.35720026, -0.8409331 ],
       [-0.67208661,  0.5422691 , -0.71034975, ..., -1.18898433,
        -0.77063987, -1.0147049 ]])

In [8]:
y_train

505    B
181    M
455    B
71     B
223    M
      ..
180    M
416    B
36     M
102    B
50     B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [9]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [10]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,

In [11]:
type(y_train)

numpy.ndarray

Numpy array to pyTorch tensors

In [12]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-1.2500, -1.4611, -1.1364,  ..., -0.1240, -0.1133,  2.8894],
        [ 1.9153,  1.7192,  2.0217,  ...,  2.6433,  1.8668,  2.4480],
        [-0.2228,  2.7019, -0.2434,  ..., -0.5762, -1.1461, -0.4013],
        ...,
        [ 0.0184,  0.5707,  0.0496,  ...,  0.4392,  1.0637,  0.9586],
        [-0.5556,  0.2865, -0.6099,  ..., -0.6264, -0.3572, -0.8409],
        [-0.6721,  0.5423, -0.7103,  ..., -1.1890, -0.7706, -1.0147]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
X_train_tensor[1].shape

torch.Size([30])

Defining the model

In [16]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_fn(self,y_pred,y):
    #Clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #Calculate loss cross entropy
    loss=-(y_train_tensor*torch.log(y_pred)+ (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

Important Parameters

In [17]:
learning_rate=0.1
epochs=50

Training Pipeline

In [18]:
#create model
model=MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_fn(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #update parameter
  with torch.no_grad():
        model.weights -=learning_rate * model.weights.grad
        model.bias -=learning_rate *model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")



Epoch: 1, Loss: 3.803004768084344
Epoch: 2, Loss: 3.7023464664130934
Epoch: 3, Loss: 3.6001408448436667
Epoch: 4, Loss: 3.489517793723027
Epoch: 5, Loss: 3.3676954263413457
Epoch: 6, Loss: 3.2391994703810223
Epoch: 7, Loss: 3.10707718872424
Epoch: 8, Loss: 2.972861147261265
Epoch: 9, Loss: 2.834418074292317
Epoch: 10, Loss: 2.692939774215773
Epoch: 11, Loss: 2.5525563436274408
Epoch: 12, Loss: 2.409609745410302
Epoch: 13, Loss: 2.269395408287616
Epoch: 14, Loss: 2.130047061528918
Epoch: 15, Loss: 1.9948698737051715
Epoch: 16, Loss: 1.8625271382222834
Epoch: 17, Loss: 1.7335525765109958
Epoch: 18, Loss: 1.6128345954153063
Epoch: 19, Loss: 1.4967600596311232
Epoch: 20, Loss: 1.3922492607987762
Epoch: 21, Loss: 1.2986136283608969
Epoch: 22, Loss: 1.2150918768035253
Epoch: 23, Loss: 1.144059457318155
Epoch: 24, Loss: 1.0848681213989437
Epoch: 25, Loss: 1.0363820079297419
Epoch: 26, Loss: 0.9970838516781041
Epoch: 27, Loss: 0.9652815668036476
Epoch: 28, Loss: 0.9393361718708686
Epoch: 29, L

In [19]:
model.bias

tensor([0.0609], dtype=torch.float64, requires_grad=True)

Evalution

In [20]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  # print(y_pred)
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5204678177833557


Defining the model using nn module


In [21]:
#create model class
import torch
import torch.nn as nn

In [22]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out

  def loss_fn(self,y_pred,y):
    #Clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #Calculate loss cross entropy
    loss=-(y_train_tensor*torch.log(y_pred)+ (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [23]:
learning_rate=0.1
epochs=50

In [25]:
#create module
model=MySimpleNN(X_train_tensor.shape[1])

#define loop
for epoch in range(epochs):

  # forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_fn(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #  zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float