<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/04pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train test splilt


In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling

In [8]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[ 1.60318575,  0.13177813,  1.60192557, ...,  2.05039274,
        -0.2311293 ,  2.44251441],
       [-0.38421282,  0.75652345, -0.42286701, ..., -0.32977087,
        -0.10491629, -0.19416776],
       [-0.21288535, -0.67685449, -0.24180144, ..., -0.38315404,
        -1.33707073, -0.43024842],
       ...,
       [ 1.10633611, -2.09372973,  1.27534612, ...,  2.2726966 ,
         2.69070172,  1.86172372],
       [-0.62407127, -1.96878067, -0.65353958, ..., -0.70103345,
        -0.68707377, -0.62707193],
       [ 1.58890846,  0.57027862,  1.56885423, ...,  1.6693004 ,
         1.81352135, -0.27429536]])

In [10]:
y_train

252    M
135    M
124    B
220    B
52     B
      ..
508    B
487    M
0      M
401    B
343    M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [14]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [32]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [16]:
type(y_train)

numpy.ndarray

Numpy array to pyTorch tensors

In [17]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [18]:
X_train_tensor

tensor([[ 1.6032,  0.1318,  1.6019,  ...,  2.0504, -0.2311,  2.4425],
        [-0.3842,  0.7565, -0.4229,  ..., -0.3298, -0.1049, -0.1942],
        [-0.2129, -0.6769, -0.2418,  ..., -0.3832, -1.3371, -0.4302],
        ...,
        [ 1.1063, -2.0937,  1.2753,  ...,  2.2727,  2.6907,  1.8617],
        [-0.6241, -1.9688, -0.6535,  ..., -0.7010, -0.6871, -0.6271],
        [ 1.5889,  0.5703,  1.5689,  ...,  1.6693,  1.8135, -0.2743]],
       dtype=torch.float64)

In [19]:
y_train_tensor.shape

torch.Size([455])

In [28]:
X_train_tensor[1].shape

torch.Size([30])

Defining the model

In [49]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_fn(self,y_pred,y):
    #Clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #Calculate loss cross entropy
    loss=-(y_train_tensor*torch.log(y_pred)+ (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

Important Parameters

In [53]:
learning_rate=0.1
epochs=50

Training Pipeline

In [54]:
#create model
model=MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_fn(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #update parameter
  with torch.no_grad():
        model.weights -=learning_rate * model.weights.grad
        model.bias -=learning_rate *model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")



Epoch: 1, Loss: 3.7977682834485034
Epoch: 2, Loss: 3.679629427540161
Epoch: 3, Loss: 3.554800178594655
Epoch: 4, Loss: 3.423029401416277
Epoch: 5, Loss: 3.285318006963859
Epoch: 6, Loss: 3.1465776107177885
Epoch: 7, Loss: 3.0079320871644564
Epoch: 8, Loss: 2.864189497475344
Epoch: 9, Loss: 2.711356664217099
Epoch: 10, Loss: 2.556872173967439
Epoch: 11, Loss: 2.3921965812958463
Epoch: 12, Loss: 2.2284210183833917
Epoch: 13, Loss: 2.067956471268493
Epoch: 14, Loss: 1.9101484456760325
Epoch: 15, Loss: 1.7580968712441798
Epoch: 16, Loss: 1.6145493808859315
Epoch: 17, Loss: 1.4793536228555688
Epoch: 18, Loss: 1.3540083853700273
Epoch: 19, Loss: 1.2435817375782576
Epoch: 20, Loss: 1.1491066086096724
Epoch: 21, Loss: 1.0709541746125024
Epoch: 22, Loss: 1.0085449612626076
Epoch: 23, Loss: 0.9602561154231936
Epoch: 24, Loss: 0.9236617863652494
Epoch: 25, Loss: 0.8960295869892453
Epoch: 26, Loss: 0.8748281962909107
Epoch: 27, Loss: 0.8580328844294008
Epoch: 28, Loss: 0.8441903922037722
Epoch: 29

In [55]:
model.bias

tensor([-0.1922], dtype=torch.float64, requires_grad=True)

Evalution

In [63]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  # print(y_pred)
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5418590307235718
