<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/05pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    # using super() we can call contructor of parent class
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear(features)
    out=self.sigmoid(out)

    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

print(features.shape[0])
#create model
model=Model(features.shape[1])

#call model for forward pass
#model.forward(features)
model(features)

10


tensor([[0.2626],
        [0.4320],
        [0.3458],
        [0.4822],
        [0.4611],
        [0.4482],
        [0.4286],
        [0.4311],
        [0.3562],
        [0.4254]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4443,  0.0576, -0.4312, -0.4126, -0.3538]], requires_grad=True)

In [ ]:
#show model bias
model.linear.bias

Parameter containing:
tensor([-0.0493], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#multiple layer network

class Model(nn.Module):

  def __init__(self,num_features):
    # using super() we can call contructor of parent class
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear1(features)
    out=self.relu(out)
    out=self.sigmoid(out)
    out=self.linear2(out)

    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

print(features.shape[0])
#create model
model=Model(features.shape[1])

#call model for forward pass
#model.forward(features)
model(features)




10


tensor([[-0.5255],
        [-0.5256],
        [-0.5255],
        [-0.5254],
        [-0.5255],
        [-0.5254],
        [-0.5254],
        [-0.5254],
        [-0.5254],
        [-0.5254]], grad_fn=<AddmmBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2338,  0.0529, -0.1762, -0.1808,  0.2971],
        [ 0.4302, -0.0782, -0.1089, -0.3862,  0.2477],
        [-0.2974, -0.2077,  0.2186, -0.0325,  0.3773]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.0020, -0.0828, -0.4632]], requires_grad=True)

In [ ]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Sigmoid: 1-3                           [10, 3]                   --
├─Linear: 1-4                            [10, 1]                   4
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#sequential containers for forward pass

class Model(nn.Module):

  def __init__(self,num_features):
    # using super() we can call contructor of parent class
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):

    out=self.network(features)

    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

print(features.shape[0])
#create model
model=Model(features.shape[1])

#call model for forward pass
#model.forward(features)
model(features)

10


tensor([[0.2609],
        [0.3121],
        [0.2907],
        [0.2805],
        [0.2615],
        [0.3318],
        [0.3498],
        [0.3263],
        [0.2816],
        [0.2933]], grad_fn=<SigmoidBackward0>)