<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/06Dataset%26DataLoader_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
#Step 1: Create a synthetic classification dataset using sklearn

X,y = make_classification(
    n_samples=10,     # Number of samples
    n_features=2,     # Number of features
    n_informative=2,  # Number of informative features
    n_redundant=0,    # Number of redundant features
    n_classes=2,      # Number of classes
    random_state=42   # For reproducibility
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape

(10,)

In [7]:
# Convert the data to Pytorch Tensor
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.float32)


In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [10]:
from torch.utils.data import Dataset,DataLoader

In [11]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self,index):

    return self.features[index],self.labels[index]

In [12]:
dataset= CustomDataset(X,y)

In [13]:
type(dataset)

__main__.CustomDataset

In [15]:
len(dataset)

10

In [16]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0.))

In [17]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [18]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-1.1402, -0.8388],
        [-1.9629, -0.9923]])
tensor([0., 0.])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-2.8954,  1.9769]])
tensor([1., 0.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [ 1.7774,  1.5116]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.7206, -0.9606]])
tensor([1., 0.])
--------------------------------------------------


In [19]:
type(dataloader)

torch.utils.data.dataloader.DataLoader

Improving the Previous work of breast Cancer with help of Dataset and DataLoader class

In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [22]:
df.shape

(569, 33)

In [23]:
df.drop(columns=['id','Unnamed: 32'], inplace= True)

In [24]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train test split

In [25]:
X_train, X_test, y_train, y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

scaling

In [26]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [27]:
X_train

array([[ 1.32264946,  0.6098787 ,  1.29410736, ...,  0.88536163,
         0.17730151, -0.03654128],
       [-0.51068148, -0.07029519, -0.57164405, ..., -1.11712208,
        -0.54480765, -0.64510149],
       [ 1.69943833,  0.07726796,  1.59542906, ...,  0.45266492,
         0.25381638, -1.34546799],
       ...,
       [-0.62596763,  0.42542476, -0.63231558, ..., -0.46272563,
         0.28569758, -0.56593919],
       [-0.71594707, -0.06568384, -0.72149052, ..., -0.70720692,
         0.22193518, -0.05303343],
       [ 1.40138146,  1.60592995,  1.51399076, ...,  1.0887138 ,
        -0.93216421,  0.452176  ]])

In [28]:
y_train

433    M
334    B
321    M
169    B
369    M
      ..
430    M
467    B
415    B
420    B
83     M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [29]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [30]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

Numpy arrays to Pytorch tensors

In [31]:
X_train_tensor=torch.from_numpy(X_train.astype(np.float32))
X_test_tensor=torch.from_numpy(X_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [32]:
X_train_tensor.shape

torch.Size([455, 30])

In [34]:
y_train_tensor.shape

torch.Size([455])

In [35]:
from torch.utils.data import Dataset,dataloader


class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self,idx):

    return self.features[idx], self.labels[idx]

In [36]:
train_dataset=CustomDataset(X_train_tensor, y_train_tensor)
test_dataset=CustomDataset(X_test_tensor, y_test_tensor)

In [37]:
train_dataset[10]

(tensor([-0.3279, -0.7620, -0.3575, -0.3932,  0.2918, -0.4666, -0.3352, -0.3801,
         -0.3026,  0.2549, -0.7051, -0.8601, -0.8005, -0.4846,  0.4891, -0.3177,
         -0.2912, -0.0850,  0.6339,  0.2995, -0.5138, -0.9310, -0.5395, -0.5085,
          0.6880, -0.2864, -0.2103, -0.1115,  0.7719,  0.6616]),
 tensor(0.))

In [48]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32, shuffle=False)

Defining the model

In [49]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num__features):

    super().__init__()
    self.linear=nn.Linear(num__features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):

    out=self.linear(features)
    out=self.sigmoid(out)

    return out

Important Parameters

In [50]:
learning_rate=0.1
epochs=25

In [51]:
#create model
model=MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_function= nn.BCELoss()


Training Pipeline

In [52]:
#define loop

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    #forward pass
    y_pred=model(batch_features)

    #loss calculate
    loss=loss_function(y_pred,batch_labels.view(-1,1))

    #clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch +1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.17412517964839935
Epoch: 2, Loss: 0.0738205760717392
Epoch: 3, Loss: 0.17595264315605164
Epoch: 4, Loss: 0.10622779279947281
Epoch: 5, Loss: 0.09300876408815384
Epoch: 6, Loss: 0.09374171495437622
Epoch: 7, Loss: 0.1387539654970169
Epoch: 8, Loss: 0.09587567299604416
Epoch: 9, Loss: 0.0590682290494442
Epoch: 10, Loss: 0.11150605976581573
Epoch: 11, Loss: 0.031418170779943466
Epoch: 12, Loss: 0.07365286350250244
Epoch: 13, Loss: 0.056997526437044144
Epoch: 14, Loss: 0.19937705993652344
Epoch: 15, Loss: 0.10242819786071777
Epoch: 16, Loss: 0.10863002389669418
Epoch: 17, Loss: 0.05998511239886284
Epoch: 18, Loss: 0.09463121742010117
Epoch: 19, Loss: 0.24750836193561554
Epoch: 20, Loss: 0.10307551175355911
Epoch: 21, Loss: 0.012805638834834099
Epoch: 22, Loss: 0.1425331085920334
Epoch: 23, Loss: 0.02306271158158779
Epoch: 24, Loss: 0.06660937517881393
Epoch: 25, Loss: 0.010578185319900513


Evaluation

In [54]:
#Model evaluation using test_loader
model.eval()  #Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    #Forward pass
    y_pred= model(batch_features)
    y_pred= (y_pred> 0.8).float() # Convert probabilities to binary predictions

    #Calculate accuracy for the current batch
    batch_accuracy =(y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

#Calculate overall accuracy
overall_accuracy =sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9375
