<a href="https://colab.research.google.com/github/pawanraje16/pyTorchLearn/blob/main/Pytorch_tensor_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available Using CPU. ")

GPU not available Using CPU. 


Creating a Tensor

In [ ]:
#using empty
a=torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.2671, 0.6852, 0.7460],
        [0.9849, 0.1783, 0.3700]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#ohter ways

#arange
print("using arange-> ",torch.arange(0,10,0.5))

#using linspace
print("using linspace-> ",torch.linspace(0,10,10))

#using eye
print("using eye-> ",torch.eye(4))

#using full
print("using full-> ",torch.full((3,3),5))

using arange->  tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])
using linspace->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
using full->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensors Shape

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #empty tensor with same shape as x

tensor([[3616445622929465956, 6066685342724926773, 3904684855656067888],
        [6501286035349452846, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to() change data type
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

Mathematical operations

1.Scalars operation

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
#addition
print(x+2)
#sub
print(x-2)
#mul
print(x*2)
#div
print(x/2)
#int div
print((x*100)//3)
#mod
print(((x*100)//3)%2)
#power
x**2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [ ]:
a=torch.rand(2,2)
b=torch.rand(2,2)
print(a)
print(b)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])
tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])


In [ ]:
#add
print(a+b)
#sub
print(a-b)
#multiply
print(a*b)
#division
print(a/b)
#power
print(a**b)
#mod
print(a%b)

tensor([[1.1753, 1.5804],
        [0.7796, 1.2794]])
tensor([[ 0.8185, -0.0673],
        [-0.3319, -0.6747]])
tensor([[0.1779, 0.6232],
        [0.1244, 0.2954]])
tensor([[5.5873, 0.9183],
        [0.4029, 0.3095]])
tensor([[0.9994, 0.7946],
        [0.4353, 0.3108]])
tensor([[0.1048, 0.7565],
        [0.2239, 0.3023]])


In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])


In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [ ]:
#sum
print(torch.sum(e))
#sum along columns
print(torch.sum(e,dim=0))
#sum along rows
torch.sum(e,dim=1)

tensor(27.)
tensor([9., 9., 9.])


tensor([10., 17.])

In [ ]:
#mean
print(torch.mean(e))
#mean along colulmns
print(torch.mean(e,dim=0))
#sum along rows
print(torch.mean(e,dim=1))

tensor(4.5000)
tensor([4.5000, 4.5000, 4.5000])
tensor([3.3333, 5.6667])


In [ ]:
#median
torch.median(e)

tensor(1.)

In [ ]:
#max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
#standard deviation
torch.std(e)

tensor(4.5935)

In [ ]:
#variance
torch.var(e)

tensor(21.1000)

In [ ]:
#argmax
torch.argmax(e)

tensor(2)

In [ ]:
#argmin
torch.argmin(e)

tensor(0)

4. Matrix operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)


print(f)
print(g)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9],
        [4, 0],
        [5, 7]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
print(f)
torch.transpose(f,0,1)

tensor([[7, 0, 0],
        [9, 5, 7]])


tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [ ]:
#determinant
torch.det(h)

tensor(184.0000)

In [ ]:
#inverse
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

5. Comparison operations

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[9, 2, 6],
        [7, 7, 8]])
tensor([[3, 6, 1],
        [5, 5, 0]])


In [ ]:
#greater than
print("i>j: ",i>j)
#less then
print("i<j: ",i<j)
#equal to
print("i=j: ",i==j)
#not equal to
print("i!=j: ",i!=j)
#greater than equal to
print("i>=j: ",i>=j)

i>j:  tensor([[ True, False,  True],
        [ True,  True,  True]])
i<j:  tensor([[False,  True, False],
        [False, False, False]])
i=j:  tensor([[False, False, False],
        [False, False, False]])
i!=j:  tensor([[True, True, True],
        [True, True, True]])
i>=j:  tensor([[ True, False,  True],
        [ True,  True,  True]])


6. Special function

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10)
k

tensor([[4, 3, 8],
        [8, 3, 3]])

In [ ]:
#log
torch.log(k)

tensor([[1.3863, 1.0986, 2.0794],
        [2.0794, 1.0986, 1.0986]])

In [ ]:
#exp
torch.exp(k)

tensor([[  54.5981,   20.0855, 2980.9580],
        [2980.9580,   20.0855,   20.0855]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 1.7321, 2.8284],
        [2.8284, 1.7321, 1.7321]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9526, 0.9997],
        [0.9997, 0.9526, 0.9526]])

In [ ]:
#softmax
torch.softmax(k.type(torch.float32), dim=0)

tensor([[0.0180, 0.5000, 0.9933],
        [0.9820, 0.5000, 0.0067]])

In [ ]:
#relu
torch.relu(k)

tensor([[4, 3, 8],
        [8, 3, 3]])

Inpalce Operations


In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])
tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])


In [ ]:
m.add_(n)

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
m

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
n

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
torch.relu(m)

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
m.relu_()

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
m

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

Copying a Tensr

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b=a # b is refrence for which is a also refrence

In [ ]:
b

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
a[0][0]=0
a

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
id(a)

136569275733904

In [ ]:
id(b)

136569275733904

In [ ]:
b=a.clone()

In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
a[0][0]=10
a

tensor([[10.0000,  0.1780,  0.3011],
        [ 0.1893,  0.9186,  0.2131]])

In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
id(a)

136569275733904

In [ ]:
id(b)

136569070922704

Tensor Operations on GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.0984, 0.0148, 0.3772],
        [0.6568, 0.3455, 0.5676]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.3387, 0.1943, 0.7024],
        [0.5965, 0.4179, 0.5184]])

In [ ]:
b=a.to(device)

In [ ]:
b+5

tensor([[5.3387, 5.1943, 5.7024],
        [5.5965, 5.4179, 5.5184]], device='cuda:0')

In [ ]:
import time

# Define the size of the matrices
size=10000 #Large size for performance comparison

# Creating time on CPU
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

# Measure time on CPU
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
end_time=time.time()
cpu_time=end_time-start_time

print(f"Time on CPU: {cpu_time:4f} seconds")

#Move matrices to GPU
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)


#Measure time on Gpu
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
end_time=time.time()
gpu_time=end_time-start_time

print(f"Time on CPU: {gpu_time:4f} seconds")

#Compare results
print("\nSpeedup (CPU time/ G) :",cpu_time/gpu_time)

Time on CPU: 27.263987 seconds
Time on CPU: 0.141549 seconds

Speedup (CPU time/ G) : 192.61150075795857


Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.8616, 0.4238, 0.0788, 0.4927],
         [0.6775, 0.4154, 0.0744, 0.5520],
         [0.2195, 0.6628, 0.2380, 0.9213]],

        [[0.2749, 0.9147, 0.7453, 0.0847],
         [0.3209, 0.6073, 0.6078, 0.6996],
         [0.7572, 0.1721, 0.3507, 0.9467]]])

In [ ]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
#unsqueze
c=torch.rand(266,266,3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [ ]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a=torch.rand([1,2,3])
a

tensor([[[0.6351, 0.1249, 0.2063],
         [0.1148, 0.5355, 0.1314]]])

In [ ]:
b=a.numpy()

In [ ]:
b

array([[[0.6350885 , 0.12492669, 0.20634085],
        [0.11482161, 0.53554845, 0.13141859]]], dtype=float32)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])